### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by CHENPINGFIONA** [muhdfirdaus/NTUC-API#36]
# Status

500 Internal Server Error Show explanation Loading time: 147
# Request headers

fingerprint: 93400b22c9dc2d1b3edad590a43ee6cb8ef9078ca5908646dac8b8d3bf83538d
timestamp: 1442996948
Origin: chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo
apikey: 1925c847-28bb-427b-a7bc-6c1b516f5c4a
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
Content-Type: application/x-www-form-urlencoded 
Accept: _/_
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6
# Response headers

Server: nginx/1.8.0 
Date: Mon, 19 Oct 2015 01:54:21 GMT 
Content-Type: text/html;charset=UTF-8 
Transfer-Encoding: chunked 
Connection: keep-alive
X-Powered-By: PHP/5.6.13
# Slim Application Error

The application could not run because of the following error:
# Details

Type: ErrorException
Code: 2
Message: DateTime::createFromFormat(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.
File: /home/ntuctest.misatravel.com/public_html/index.php
Line: 110
# Trace
#0 [internal function]: Slim\Slim::handleErrors(2, 'DateTime::creat...', '/home/ntuctest....', 110, Array)
#1 /home/ntuctest.misatravel.com/public_html/index.php(110): DateTime::createFromFormat('Ymd', '20150923')
#2 /home/ntuctest.misatravel.com/public_html/index.php(177): validateDate(20150923, 'Ymd')
#3 [internal function]: {closure}()
#4 /home/ntuctest.misatravel.com/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#5 /home/ntuctest.misatravel.com/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#6 /home/ntuctest.misatravel.com/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#7 /home/ntuctest.misatravel.com/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#8 /home/ntuctest.misatravel.com/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#9 /home/ntuctest.misatravel.com/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#10 /home/ntuctest.misatravel.com/public_html/index.php(229): Slim\Slim->run()
#11 {main}

**Comment by muhdfirdaus** [comment]
The validateDate function suppose to test the date that already included in the header to the api/updates/ is it in the right format (YYYYmmdd) or not. If I may ask, why does it need the timezone setting?

**Comment by josergcatmisatravelcom** [comment]
@muhdfirdaus it is required by the function you are using

**Comment by parisqian-misa** [comment]
@muhdfirdaus Can add `date_default_timezone_set("Asia/Singapore");`
Or if you feels more familiar with `php.ini` file, do search for `data.timezone` setting, and change it to

``` INI
date.timezone = Asia/Singapore
```

see: http://php.net/manual/en/timezones.asia.php 

Also, if you want to ignore errors in production environment,
you can add at the beginning of your code

``` php
error_reporting(0);
```

and use following statement in develop environment to see all the error reports during debugging.

``` php
// Report all errors except E_NOTICE
error_reporting(E_ALL & ~E_NOTICE);
```

**Comment by josergcatmisatravelcom** [comment]
@muhdfirdaus @parisqian-misa use <pre>date_default_timezone_set("Asia/Singapore");</pre> to avoid to change settings in the server and make the system more robust to the deployment failures.
